
package GUI;

import Sources.Admin;
import Sources.Course;
import Sources.Course2Admin;
import Sources.Student;
import Sources.Teacher;
import Sources.User;
import java.awt.Component;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class AdminPage extends javax.swing.JFrame {
    
    ArrayList<User> kullaniciListesi;
    ArrayList<Course> dersListesi;
    Admin gecerliAdmin;
    ArrayList<Course2Admin>alinacakDersler;
    DefaultListModel listModel;

    /**
     * Creates new form AdminPage
     */
    public AdminPage(ArrayList<User> kullaniciListesi, ArrayList<Course> dersListesi,Admin gecerliAdmin, ArrayList<Course2Admin>alinacakDersler) {
        
        this.kullaniciListesi = kullaniciListesi;
        this.dersListesi = dersListesi;
        this.gecerliAdmin = gecerliAdmin;
        this.alinacakDersler = alinacakDersler;
        listModel = new DefaultListModel();
        setVisible(true);
        initComponents();
        for (int sayac = 0; sayac < alinacakDersler.size(); sayac++) {
            cmBoxAdminOgrenciSec.addItem(alinacakDersler.get(sayac).getOgrenci().getName()+ " " +alinacakDersler.get(sayac).getOgrenci().getSurname());
        }
        for (int sayac = 0; sayac < kullaniciListesi.size(); sayac++) {
            if (kullaniciListesi.get(sayac).getClass().equals(Student.class)) {
                cmBoxAdminOgrenciRapor.addItem(kullaniciListesi.get(sayac).getName()+ " " + kullaniciListesi.get(sayac).getSurname());
            }
        }
    }

    private AdminPage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdminOturumuKapat = new javax.swing.JButton();
        cmBoxAdminOgrenciSec = new javax.swing.JComboBox<>();
        lblAdminOgrenciSec = new javax.swing.JLabel();
        btnAdminDersOnaylama = new javax.swing.JButton();
        btnAdminDersOnayla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmBoxAdminOgrenciRapor = new javax.swing.JComboBox<>();
        btnAdminRaporGonder = new javax.swing.JButton();
        btnAdminSec = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAdmin = new javax.swing.JList<>();
        btnAdminVeri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdminOturumuKapat.setText("Logout");
        btnAdminOturumuKapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminOturumuKapatActionPerformed(evt);
            }
        });

        lblAdminOgrenciSec.setText("Select student:");

        btnAdminDersOnaylama.setText("Disapprove");
        btnAdminDersOnaylama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDersOnaylamaActionPerformed(evt);
            }
        });

        btnAdminDersOnayla.setText("Approve");
        btnAdminDersOnayla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDersOnaylaActionPerformed(evt);
            }
        });

        jLabel1.setText("Send report to student:");

        btnAdminRaporGonder.setText("Send");
        btnAdminRaporGonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminRaporGonderActionPerformed(evt);
            }
        });

        btnAdminSec.setText("Select");
        btnAdminSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminSecActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listAdmin);

        btnAdminVeri.setText("Update to Database");
        btnAdminVeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminVeriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdminOturumuKapat)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cmBoxAdminOgrenciRapor, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdminVeri, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnAdminRaporGonder))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdminDersOnaylama)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminDersOnayla))
                    .addComponent(lblAdminOgrenciSec)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(cmBoxAdminOgrenciSec, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAdminSec))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnAdminOturumuKapat)
                .addGap(35, 35, 35)
                .addComponent(lblAdminOgrenciSec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmBoxAdminOgrenciSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminSec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminDersOnaylama)
                    .addComponent(btnAdminDersOnayla))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmBoxAdminOgrenciRapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnAdminRaporGonder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdminVeri)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminSecActionPerformed
        String kisiAdi = cmBoxAdminOgrenciSec.getSelectedItem().toString();
        for (int sayac = 0; sayac < alinacakDersler.size(); sayac++) {
            Course2Admin c = alinacakDersler.get(sayac);
            if (kisiAdi.equals(c.getOgrenci().getName()+" "+c.getOgrenci().getSurname())) {
                
                for (int sayac2 = 0; sayac2 < c.getDersler().size(); sayac2++) {
                    listModel.addElement(c.getDersler().get(sayac2).getName());
                    listAdmin.setModel(listModel);
                }
            }
        }
    }//GEN-LAST:event_btnAdminSecActionPerformed

    private void btnAdminDersOnaylaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDersOnaylaActionPerformed
        for (int sayac = 0; sayac < alinacakDersler.size(); sayac++) {
            Course2Admin c = alinacakDersler.get(sayac);
            if(cmBoxAdminOgrenciSec.getSelectedItem().toString().equals(c.getOgrenci().getName()+" "+c.getOgrenci().getSurname()))
            {
                Student s = c.getOgrenci();
                for (int sayac2 = 0; sayac2 < c.getDersler().size(); sayac2++) {
                    s.dersEkle(c.getDersler().get(sayac2));
                }
                alinacakDersler.remove(sayac);
                break;
            }
        }
        listModel.removeAllElements();
        listAdmin.setModel(listModel);
        cmBoxAdminOgrenciSec.removeAllItems();
        for (int sayac = 0; sayac < alinacakDersler.size(); sayac++) {
            cmBoxAdminOgrenciSec.addItem(alinacakDersler.get(sayac).getOgrenci().getName()+ " " + alinacakDersler.get(sayac).getOgrenci().getSurname());
        }
        JOptionPane.showMessageDialog(null, "\n" + 	"Course Approved");
    }//GEN-LAST:event_btnAdminDersOnaylaActionPerformed

    private void btnAdminOturumuKapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminOturumuKapatActionPerformed
        GirisEkrani g = new GirisEkrani(kullaniciListesi, dersListesi, alinacakDersler);
        dispose();
    }//GEN-LAST:event_btnAdminOturumuKapatActionPerformed

    private void btnAdminDersOnaylamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDersOnaylamaActionPerformed
        for (int sayac = 0; sayac < alinacakDersler.size(); sayac++) {
            Course2Admin c = alinacakDersler.get(sayac);
            if(cmBoxAdminOgrenciSec.getSelectedItem().toString().equals(c.getOgrenci().getName()+" "+c.getOgrenci().getSurname()))
            {
                alinacakDersler.remove(sayac);
                break;
            }
        }
        listModel.removeAllElements();
        listAdmin.setModel(listModel);
        cmBoxAdminOgrenciSec.removeAllItems();
        for (int sayac = 0; sayac < alinacakDersler.size(); sayac++) {
            cmBoxAdminOgrenciSec.addItem(alinacakDersler.get(sayac).getOgrenci().getName()+ " " + alinacakDersler.get(sayac).getOgrenci().getSurname());
        }
        JOptionPane.showMessageDialog(null, "Courses Refused");
    }//GEN-LAST:event_btnAdminDersOnaylamaActionPerformed

    private void btnAdminRaporGonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminRaporGonderActionPerformed
        String kisi = cmBoxAdminOgrenciRapor.getSelectedItem().toString();
        for (int sayac = 0; sayac < kullaniciListesi.size(); sayac++) {
            if (kisi.equals(kullaniciListesi.get(sayac).getName()+ " " + kullaniciListesi.get(sayac).getSurname())) {
                Student s = (Student) kullaniciListesi.get(sayac);
                s.setYoneticiMesaji("Message from admin! You can add or drop courses.");
                break;
            }
        }
        JOptionPane.showMessageDialog(null, "Report Sended");
    }//GEN-LAST:event_btnAdminRaporGonderActionPerformed

    private void btnAdminVeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminVeriActionPerformed
        try {
            DosyayiGuncelle(kullaniciListesi, dersListesi);
            JOptionPane.showMessageDialog(null, "Database updated successfully");
        } catch (IOException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdminVeriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }
    
    private void DosyayiGuncelle(ArrayList<User> kullaniciListesi, ArrayList<Course> dersListesi) throws FileNotFoundException, IOException
    {
        File fout = new File("veriler.txt");
        FileOutputStream fos = new FileOutputStream(fout);
        BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(fos));
        for (int sayac = 0; sayac < kullaniciListesi.size(); sayac++) {
            Object o = kullaniciListesi.get(sayac);
            if (o.getClass().equals(Student.class))
            {
                Student s = (Student)o;
                bw.write("S"+"~"+s.getName()+"~"+s.getSurname()+"~"+s.getTC()+"~"+s.getID()+"~"+s.getPassword()+"~"+s.getBirthYear());
                for (int sayac2 = 0; sayac2 < s.getDersler().size(); sayac2++) {
                    bw.write("~" + s.getDersler().get(sayac2).getCode()+"~"+s.getDersler().get(sayac2).getName());
                }
                bw.newLine();
            }
            else if (o.getClass().equals(Admin.class))
            {
                Admin s = (Admin)o;
                bw.write("A"+"~"+s.getName()+"~"+s.getSurname()+"~"+s.getTC()+"~"+s.getID()+"~"+s.getPassword());
                bw.newLine();
            }
            else
            {
                Teacher s = (Teacher)o;
                bw.write("T"+"~"+s.getName()+"~"+s.getSurname()+"~"+s.getTC()+"~"+s.getID()+"~"+s.getPassword());
                bw.newLine();
            }
        }
        if (dersListesi.size() > 0) {
            bw.write("C");
            for (int sayac = 0; sayac < dersListesi.size(); sayac++) {
            bw.write("~"+dersListesi.get(sayac).getCode()+"~"+dersListesi.get(sayac).getName()+"~"+dersListesi.get(sayac).isStatus());
            }
        }
        bw.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminDersOnayla;
    private javax.swing.JButton btnAdminDersOnaylama;
    private javax.swing.JButton btnAdminOturumuKapat;
    private javax.swing.JButton btnAdminRaporGonder;
    private javax.swing.JButton btnAdminSec;
    private javax.swing.JButton btnAdminVeri;
    private javax.swing.JComboBox<String> cmBoxAdminOgrenciRapor;
    private javax.swing.JComboBox<String> cmBoxAdminOgrenciSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdminOgrenciSec;
    private javax.swing.JList<String> listAdmin;
    // End of variables declaration//GEN-END:variables
}
