
package GUI;

import Sources.Course;
import Sources.Course2Admin;
import Sources.Teacher;
import Sources.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class InstructorPage extends javax.swing.JFrame {
     ArrayList<User> kullaniciListesi;
    ArrayList<Course> dersListesi;
    Teacher gecerliOgretmen;
    ArrayList<Course2Admin>alinacakDersler;

    /**
     * Creates new form InstructorPage
     */
    public InstructorPage(ArrayList<User> kullaniciListesi, ArrayList<Course> dersListesi, Teacher teacher,ArrayList<Course2Admin>alinacakDersler) {
        this.kullaniciListesi = kullaniciListesi;
        this.dersListesi = dersListesi;
        this.gecerliOgretmen = teacher;
        this.alinacakDersler = alinacakDersler;
        setVisible(true);
        initComponents();
        
        for (int sayac = 0; sayac < dersListesi.size(); sayac++) {
            Course c = dersListesi.get(sayac);
            if (!c.isStatus())
            {
                cmBoxInstructorAcilabilir.addItem(c.getName());
            }
        }
    }

    InstructorPage() {
        
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInstructorOturumuKapat = new javax.swing.JButton();
        lblInstructorAcilabilir = new javax.swing.JLabel();
        cmBoxInstructorAcilabilir = new javax.swing.JComboBox<>();
        btnInstructorDersAc = new javax.swing.JButton();
        lblInstructorDersEkle = new javax.swing.JLabel();
        txfieldInstructorDersEkle = new javax.swing.JTextField();
        btnInstructorEkle = new javax.swing.JButton();
        txfieldInstructorDersKodu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInstructorOturumuKapat.setText("Logout");
        btnInstructorOturumuKapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructorOturumuKapatActionPerformed(evt);
            }
        });

        lblInstructorAcilabilir.setText("Openable Courses:");

        btnInstructorDersAc.setText("Open Course");
        btnInstructorDersAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructorDersAcActionPerformed(evt);
            }
        });

        lblInstructorDersEkle.setText("Add Course:");

        btnInstructorEkle.setText("Add");
        btnInstructorEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructorEkleActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("Code:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(btnInstructorOturumuKapat)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnInstructorDersAc, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblInstructorAcilabilir, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmBoxInstructorAcilabilir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInstructorEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lblInstructorDersEkle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfieldInstructorDersEkle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfieldInstructorDersKodu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnInstructorOturumuKapat)
                .addGap(46, 46, 46)
                .addComponent(lblInstructorAcilabilir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmBoxInstructorAcilabilir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInstructorDersAc)
                .addGap(61, 61, 61)
                .addComponent(lblInstructorDersEkle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfieldInstructorDersEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfieldInstructorDersKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addComponent(btnInstructorEkle)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInstructorDersAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructorDersAcActionPerformed
        String acilacakDers = cmBoxInstructorAcilabilir.getSelectedItem().toString();
        for (int sayac = 0; sayac < dersListesi.size(); sayac++) {
            Course c = dersListesi.get(sayac);
            if (c.getName().equals(acilacakDers)) {
                c.setStatus(true);
                break;
            }
        }
        cmBoxInstructorAcilabilir.removeAllItems();
        for (int sayac = 0; sayac < dersListesi.size(); sayac++) {
            Course c = dersListesi.get(sayac);
            if (!c.isStatus())
            {
                cmBoxInstructorAcilabilir.addItem(c.getName());
            }
        }
        JOptionPane.showMessageDialog(null, "Course Opened Successfully");
    }//GEN-LAST:event_btnInstructorDersAcActionPerformed

    private void btnInstructorEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructorEkleActionPerformed
        Course yeniDers = new Course(txfieldInstructorDersKodu.getText(),txfieldInstructorDersEkle.getText(),true);
        dersListesi.add(yeniDers);
        txfieldInstructorDersEkle.setText("");
        txfieldInstructorDersKodu.setText("");
        JOptionPane.showMessageDialog(null, "New Course Added");
    }//GEN-LAST:event_btnInstructorEkleActionPerformed

    private void btnInstructorOturumuKapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructorOturumuKapatActionPerformed
        GirisEkrani g = new GirisEkrani(kullaniciListesi, dersListesi,alinacakDersler);
        dispose();
    }//GEN-LAST:event_btnInstructorOturumuKapatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInstructorDersAc;
    private javax.swing.JButton btnInstructorEkle;
    private javax.swing.JButton btnInstructorOturumuKapat;
    private javax.swing.JComboBox<String> cmBoxInstructorAcilabilir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblInstructorAcilabilir;
    private javax.swing.JLabel lblInstructorDersEkle;
    private javax.swing.JTextField txfieldInstructorDersEkle;
    private javax.swing.JTextField txfieldInstructorDersKodu;
    // End of variables declaration//GEN-END:variables
}
