
package GUI;

import Sources.Admin;
import Sources.Course;
import Sources.Course2Admin;
import Sources.Student;
import Sources.Teacher;
import Sources.User;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;


public class KayitSayfasi extends javax.swing.JFrame {

    /**
     * Creates new form KayitSayfasi
     */
    ArrayList<User> kullaniciListesi;
    ArrayList<Course> dersListesi;
    ArrayList<Course2Admin>alinacakDersler;
    ButtonGroup buttonGroup = new ButtonGroup();
    public KayitSayfasi(ArrayList<User> kullaniciListesi,ArrayList<Course> dersListesi, ArrayList<Course2Admin>alinacakDersler) {
        this.dersListesi = dersListesi;
        this.alinacakDersler = alinacakDersler;
        this.kullaniciListesi = kullaniciListesi;
        setVisible(true);
        initComponents();
        buttonGroup.add(rbtnKayitAdmin);
        buttonGroup.add(rbtnKayitStudent);
        buttonGroup.add(rbtnkayitInstructor);
        jLabel5.setVisible(false);
        txfieldKayitDogumYili.setVisible(false);
    }

    private KayitSayfasi() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnKayitAdmin = new javax.swing.JRadioButton();
        lblKayitTip = new javax.swing.JLabel();
        rbtnkayitInstructor = new javax.swing.JRadioButton();
        rbtnKayitStudent = new javax.swing.JRadioButton();
        txfieldKayitAdSoyad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfieldKayitID = new javax.swing.JTextField();
        txfieldKayitTC = new javax.swing.JTextField();
        txfieldKayitSifre = new javax.swing.JPasswordField();
        btnKayitKaydol = new javax.swing.JButton();
        btnKayitGiriseDon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txfieldKayitDogumYili = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txfieldKayitSoyad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbtnKayitAdmin.setText("Admin");

        lblKayitTip.setText("Select to registiration ype");

        rbtnkayitInstructor.setText("Instructor");

        rbtnKayitStudent.setText("Student");
        rbtnKayitStudent.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnKayitStudentStateChanged(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("User ID:");

        jLabel3.setText("Identity Number");

        jLabel4.setText("Password:");

        btnKayitKaydol.setText("Register");
        btnKayitKaydol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitKaydolActionPerformed(evt);
            }
        });

        btnKayitGiriseDon.setText("Back to Login Page");
        btnKayitGiriseDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitGiriseDonActionPerformed(evt);
            }
        });

        jLabel5.setText("Birth year:");

        jLabel6.setText("Surname:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblKayitTip))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(rbtnKayitAdmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnkayitInstructor)
                                .addGap(34, 34, 34)
                                .addComponent(rbtnKayitStudent))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txfieldKayitDogumYili, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(txfieldKayitTC, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txfieldKayitSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txfieldKayitSoyad, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(txfieldKayitAdSoyad)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txfieldKayitID, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnKayitGiriseDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKayitKaydol, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblKayitTip)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnKayitAdmin)
                    .addComponent(rbtnkayitInstructor)
                    .addComponent(rbtnKayitStudent))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfieldKayitAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txfieldKayitSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfieldKayitID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfieldKayitTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfieldKayitSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txfieldKayitDogumYili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKayitKaydol)
                    .addComponent(btnKayitGiriseDon))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKayitKaydolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitKaydolActionPerformed
        if (rbtnKayitAdmin.isSelected()) {
            Admin yeniAdmin = new  Admin(txfieldKayitAdSoyad.getText(), txfieldKayitSoyad.getText(), txfieldKayitTC.getText(), txfieldKayitID.getText(), txfieldKayitSifre.getText());
            kullaniciListesi.add(yeniAdmin);
        }
        else if (rbtnkayitInstructor.isSelected())
        {
            Teacher yeniOgretmen = new  Teacher(txfieldKayitAdSoyad.getText(), txfieldKayitSoyad.getText(), txfieldKayitTC.getText(), txfieldKayitID.getText(), txfieldKayitSifre.getText());
            kullaniciListesi.add(yeniOgretmen);
        }
        else
        {
            Student yeniAdmin = new  Student(txfieldKayitAdSoyad.getText(), txfieldKayitSoyad.getText(), txfieldKayitTC.getText(), txfieldKayitID.getText(), txfieldKayitSifre.getText(),Integer.parseInt(txfieldKayitDogumYili.getText()));
            kullaniciListesi.add(yeniAdmin);
        }
        
        JOptionPane.showMessageDialog(null, "Registration Completed");
        GirisEkrani g = new GirisEkrani(kullaniciListesi, dersListesi, alinacakDersler);
        dispose();
    }//GEN-LAST:event_btnKayitKaydolActionPerformed

    private void rbtnKayitStudentStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnKayitStudentStateChanged
        if (rbtnKayitStudent.isSelected()) {
            jLabel5.setVisible(true);
            txfieldKayitDogumYili.setVisible(true);
        }
        else
        {
            jLabel5.setVisible(false);
            txfieldKayitDogumYili.setVisible(false);
        }
    }//GEN-LAST:event_rbtnKayitStudentStateChanged

    private void btnKayitGiriseDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitGiriseDonActionPerformed
        GirisEkrani g = new GirisEkrani(kullaniciListesi, dersListesi, alinacakDersler);
        dispose();
    }//GEN-LAST:event_btnKayitGiriseDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitSayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKayitGiriseDon;
    private javax.swing.JButton btnKayitKaydol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblKayitTip;
    private javax.swing.JRadioButton rbtnKayitAdmin;
    private javax.swing.JRadioButton rbtnKayitStudent;
    private javax.swing.JRadioButton rbtnkayitInstructor;
    private javax.swing.JTextField txfieldKayitAdSoyad;
    private javax.swing.JTextField txfieldKayitDogumYili;
    private javax.swing.JTextField txfieldKayitID;
    private javax.swing.JPasswordField txfieldKayitSifre;
    private javax.swing.JTextField txfieldKayitSoyad;
    private javax.swing.JTextField txfieldKayitTC;
    // End of variables declaration//GEN-END:variables
}
