
package GUI;

import Sources.Course;
import Sources.Course2Admin;
import Sources.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class SifremiUnuttumSayfasi extends javax.swing.JFrame {
    
    ArrayList<User> kullaniciListesi;
    ArrayList<Course> dersListesi;
    ArrayList<Course2Admin>alinacakDersler;
    User gecerliKullanici;

    /**
     * Creates new form SifremiUnuttumSayfasi
     */
    public SifremiUnuttumSayfasi(ArrayList<User> kullaniciListesi,ArrayList<Course> dersListesi, ArrayList<Course2Admin>alinacakDersler) {
        this.dersListesi = dersListesi;
        this.alinacakDersler = alinacakDersler;
        this.kullaniciListesi = kullaniciListesi;
        setVisible(true);
        initComponents();
        jLabel2.setVisible(false);
        btnSifreDegistir.setVisible(false);
        txfieldSifreYeni.setVisible(false);
    }

    private SifremiUnuttumSayfasi() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txfieldSifreTC = new javax.swing.JTextField();
        btnSifreDogrula = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblSifreDurumMesaji = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfieldSifreYeni = new javax.swing.JPasswordField();
        btnSifreDegistir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Please write to identity number:");

        btnSifreDogrula.setText("Authenication");
        btnSifreDogrula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSifreDogrulaActionPerformed(evt);
            }
        });

        jButton1.setText("Back to Login Page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Please write new password:");

        btnSifreDegistir.setText("Change password");
        btnSifreDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSifreDegistirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(120, 120, 120))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txfieldSifreTC, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSifreDogrula, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSifreDurumMesaji)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txfieldSifreYeni, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSifreDegistir, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txfieldSifreTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSifreDogrula)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(lblSifreDurumMesaji)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txfieldSifreYeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSifreDegistir)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GirisEkrani g = new GirisEkrani(kullaniciListesi, dersListesi, alinacakDersler);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSifreDogrulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSifreDogrulaActionPerformed
        String TC = txfieldSifreTC.getText();
        boolean bulunduMu =false;
        for (int sayac = 0; sayac < kullaniciListesi.size(); sayac++) {
            if (kullaniciListesi.get(sayac).getTC().equals(TC)) {
                gecerliKullanici = kullaniciListesi.get(sayac);
                bulunduMu =true;
                break;
            }
        }
        if (bulunduMu) {
            jLabel2.setVisible(true);
            txfieldSifreYeni.setVisible(true);
            btnSifreDegistir.setVisible(true);
            txfieldSifreTC.setVisible(false);
            jLabel1.setText("Confirmed TC: " + TC);
            btnSifreDogrula.setVisible(false);
            JOptionPane.showMessageDialog(null, "TC Identity Number Verified");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "TC Identity Number not Found");
        }
    }//GEN-LAST:event_btnSifreDogrulaActionPerformed

    private void btnSifreDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSifreDegistirActionPerformed
        gecerliKullanici.setPassword(txfieldSifreYeni.getText());
        JOptionPane.showMessageDialog(null, "Password Successfully Changed");
        GirisEkrani g = new GirisEkrani(kullaniciListesi, dersListesi, alinacakDersler);
        dispose();
    }//GEN-LAST:event_btnSifreDegistirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SifremiUnuttumSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SifremiUnuttumSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SifremiUnuttumSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SifremiUnuttumSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SifremiUnuttumSayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSifreDegistir;
    private javax.swing.JButton btnSifreDogrula;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblSifreDurumMesaji;
    private javax.swing.JTextField txfieldSifreTC;
    private javax.swing.JPasswordField txfieldSifreYeni;
    // End of variables declaration//GEN-END:variables
}
